name: flutter_story_list
description: A Flutter package to create Facebook's style Story List. It will be useful for your awesome app.
version: 1.0.4
homepage: https://minhhung2556.medium.com
repository: https://gitlab.com/romantic_project/flutter_story_list.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
